# Generated by Django 4.2.5 on 2023-09-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
