# Generated by Django 4.2.5 on 2023-09-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_user'),
        ('main', '0003_item_user_id'),
    ]

    operations = [
    ]
