# Generated by Django 4.2.5 on 2023-09-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_0003_item_user_0003_item_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_id',
        ),
    ]
